### ISSUE TITLE
After container restart, no longer able to connect to DB

### ISSUE THREAD

**Issue by rtrauntvein** [sameersbn/docker-openfire#8]
Configured and initially setup with MySQL connection.  Was able to connect and run through Openfire setup initially. Persistent volume is mounted at /data

After a "docker stop openfire" it then would not start.  `docker logs` output below:

```
docker logs openfire
Starting openfire...
Openfire 3.9.3 [May 19, 2015 11:07:08 PM]
Admin console listening at http://b5753eac9308:9090
Missing database schema for openfire. Attempting to install...
Database update successful.
...
Database setup or configuration error: Please verify your database settings and check the logs/error.log file for detailed error messages.
java.lang.IllegalArgumentException: java.sql.SQLException: ConnectionManager.getConnection() failed to obtain a connection after 11 retries. The exception from the last attempt is as follows: java.sql.SQLException: Access denied for user 'imuser'@'x.x.x.x' (using password: YES)
	at org.jivesoftware.openfire.XMPPServer.verifyDataSource(XMPPServer.java:759)
	at org.jivesoftware.openfire.XMPPServer.start(XMPPServer.java:472)
	at org.jivesoftware.openfire.XMPPServer.<init>(XMPPServer.java:197)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.jivesoftware.openfire.starter.ServerStarter.start(ServerStarter.java:113)
	at org.jivesoftware.openfire.starter.ServerStarter.main(ServerStarter.java:58)
Caused by: java.sql.SQLException: ConnectionManager.getConnection() failed to obtain a connection after 11 retries. The exception from the last attempt is as follows: java.sql.SQLException: Access denied for user 'imuser'@'x.x.x.x' (using password: YES)
	at org.jivesoftware.database.DbConnectionManager.getConnection(DbConnectionManager.java:151)
	at org.jivesoftware.openfire.XMPPServer.verifyDataSource(XMPPServer.java:749)
	... 9 more
Error starting the server. Please check the log files for more information.
Server halted
Starting openfire...
Database setup or configuration error: Please verify your database settings and check the logs/error.log file for detailed error messages.
java.lang.IllegalArgumentException: java.sql.SQLException: ConnectionManager.getConnection() failed to obtain a connection after 11 retries. The exception from the last attempt is as follows: java.sql.SQLException: Access denied for user 'imuser'@'66.162.157.233' (using password: YES)
	at org.jivesoftware.openfire.XMPPServer.verifyDataSource(XMPPServer.java:759)
	at org.jivesoftware.openfire.XMPPServer.start(XMPPServer.java:472)
	at org.jivesoftware.openfire.XMPPServer.<init>(XMPPServer.java:197)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.jivesoftware.openfire.starter.ServerStarter.start(ServerStarter.java:113)
	at org.jivesoftware.openfire.starter.ServerStarter.main(ServerStarter.java:58)
Caused by: java.sql.SQLException: ConnectionManager.getConnection() failed to obtain a connection after 11 retries. The exception from the last attempt is as follows: java.sql.SQLException: Access denied for user 'imuser'@'X.X.X.X' (using password: YES)
	at org.jivesoftware.database.DbConnectionManager.getConnection(DbConnectionManager.java:151)
	at org.jivesoftware.openfire.XMPPServer.verifyDataSource(XMPPServer.java:749)
	... 9 more
Error starting the server. Please check the log files for more information.
Server halted
```

Host info:
Ubuntu 14.04 

```
docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Comment by sameersbn** [comment]
@rtrauntvein does removing the container and starting it again work by any chance? So far I have no had any issues with the `3.9.3-xx` releases.

**Comment by rtrauntvein** [comment]
I get the same thing, it is no longer able to connect to the DB.

**Comment by sameersbn** [comment]
@rtrauntvein maybe something went wrong in your setup. I used the following docker-compose file

```bash
postgresql:
  image: sameersbn/postgresql:latest
  environment:
    - DB_USER=openfire
    - DB_PASS=password
    - DB_NAME=openfiredb
  ports:
    - "172.17.42.1:5432:5432"
  volumes:
    - /srv/docker/openfire/postgresql:/var/lib/postgresql
openfire:
  image: sameersbn/openfire:3.9.3-2
  ports:
    - "9090:9090"
    - "5222:5222"
    - "7777:7777"
  volumes:
    - /srv/docker/openfire/openfire:/data
```

I logged in to openfire and setup the application to use a postgresql connection at the `172.17.42.1:5432` address. Once done I am able to stop / delete the container and relaunch using docker-compose without any problems.

Can you try it out.

**Comment by rtrauntvein** [comment]
We were using MySQL - I will test it on Postgresql and let you know how it works.

**Comment by sameersbn** [comment]
@rtrauntvein Using mysql should also work, just change the docker-compose file to use mysql.

**Comment by gaomd** [comment]
@rtrauntvein I'm using PostgreSQL and I'm facing the same problem: Unable to connect to DB after container restarted.

**Comment by gaomd** [comment]
Temporary workaroud:

In `/data/openfire/etc/security.xml` file, comment out `security.encrypt.key.property`:

```xml
<security>
  <encrypt>
    <key>
     <property>
      <!-- 
        This list includes the names of properties that have been marked for
        encryption. Any XML properties (from openfire.xml) that are listed here 
        will be encrypted automatically upon first use. Other properties 
        (already in the database) can be added to this list at runtime via the 
        "System Properties" page in the Openfire console.
      -->
      <!-- COMMENT OUT THESE F***ING ELEMENTS.
      <name>database.defaultProvider.username</name>  
      <name>database.defaultProvider.password</name>  
      <name>xmpp.domain</name> 
      -->
    </property>
  </encrypt>
</security>
```

In `/data/openfire/etc/openfire.xml` file, remove `encrypted="true"` attribute of `username`, `password` element, and set their values to plaintext:

```xml
<jive>
  <database>
    <defaultProvider>
      <username>dbuser</username>
      <password>dbpass</password>
    </defaultProvider>
  </database>
</jive>
```

**Comment by rtrauntvein** [comment]
So it ended up being an "&" in the database password causing the issue.

Thanks to @gaomd suggestion I was able to get java to spit out an error on line 43 of the server.xml about an invalid & character.

Changing our DB user's password fixed the issue. There may be some bug there but I am not sure if it would be upstream openfire or related to this image.

Thanks for the help!

**Comment by sameersbn** [comment]
@rtrauntvein this is probably an issue with openfire itself. The image by itself does not ask you to provide any database connection settings. You specify this while setting up openfire from the web ui. I think the problem is that openfire saves its data in xml files and as you must already be aware, xml requires special formatting of characters such as `&`. Probably this should be reported to openfire devs.

**Comment by gaomd** [comment]
@rtrauntvein I surely have an "`&`" in my database password, thanks for you solution.

@sameersbn Openfire seems have a serious issue dealing with "&", even with property encryption enabled, the encrypted database password looks like `aZaZaZaZ aZaZaZ=`, notice there is an space between the string. I agree it's an issue with Openfire itself.

**Comment by bmulpuri** [comment]
I had a similar problem. I use MySQL and I was getting connectivity errors when I stopped and started the container or recreated the container. I was finally able to solve this by adding the following entries to security.xml file (kind of opposite of what was suggested @gaomd in an earlier post).

<name>database.defaultProvider.username</name>  
<name>database.defaultProvider.password</name>

I am just wondering if there any configuration in openfire that allows me to specify this without having to manually add these entries to the security.xml file after initial configuration?

**Comment by khanimdad** [comment]
I have this, and still not sure how to fix it.

I am using Rails with Postgres and the latest version of Docker, only reinstalling fix the issue, but again after system reboot
it stops working ie web service can't connect to db server.

Any idea what could be issue?
